### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by moishinetzer** [mattpocock/pkg-demo#2]
Hey matt! Thanks for this amazing template/tutorial. 

How would you recommend extending this as a monorepo and what would be the easiest way to go about it without adding too much complexity?

**Comment by moishinetzer** [comment]
@mattpocock any chance we could get your take on this?

**Comment by mattpocock** [comment]
If I do this, I'll do it as a separate project!

I wrote a LOT about monorepos when I worked at Vercel:

https://turbo.build/repo/docs/getting-started/create-new
